# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.cache/wt [current_project]
set_property parent.project_path C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/VOICE_CAPTURER.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/VGA_DISPLAY.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Draw_Waveform.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Draw_Background.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Voice_Scope_TOP.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/TestWave_Gen.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/clk_div.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/volume_indicator.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/clk_10.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/Generate_Color.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/btn_press_clk_gen.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/is_btn_press.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/dflipflop.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/volume_indicator_count.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/frequency_calculator.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/displayfreqcount.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/unlockfeature.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/intensity_shift_gen.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/draw_lock_object.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/create_ring_object.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/clk_40.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/unlock_featureSW6.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/frequency_text.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/menu_text_gen.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/change_switches.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/volume_bar.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/volume_bar_text.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/unlockfeaturesw62.v
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/new/create_sphere.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/VGA_CONTROL.vhd
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/CLK_108M.vhd
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Pixel_On_Text2.vhd
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Pixel_On_Text.vhd
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/commonPak.vhd
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/wrapper.vhd
  C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Font_Rom.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/constrs_1/imports/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/saiab/Downloads/Audio_Viz_Project_Template/Audio_Viz_Project_Template.srcs/constrs_1/imports/new/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Voice_Scope_TOP -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Voice_Scope_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Voice_Scope_TOP_utilization_synth.rpt -pb Voice_Scope_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
